runtime: go
api_version: go1
service: default

instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 0

handlers: 
- url: /.*
  static_files: static/index.html
  upload: static/.*
